---

default:
  image: docker:stable

services:
  - docker:dind

stages:
 - dev
 - prod

deploy:traefik:dev:
  stage: dev
  tags:
    - dev-runner
  when: manual
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker stack deploy --with-registry-auth -c docker-compose.ingress.yml ingress

deploy:traefik:prod:
  stage: prod
  tags:
    - prod-runner
  when: manual
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker stack deploy --with-registry-auth -c docker-compose.ingress.yml ingress